services:
  - type: web
    name: spedex-backend
    env: docker
    dockerContext: .
    dockerFilePath: Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8080
